
# [language-server.erlang-lsp]
# command = "elp"
# args = ["server"]

# [[language]]
# name = "erlang"
# language-servers = ["erlang-lsp"]

#[language-server.rust-analyzer.config.check]
#command = "clippy"

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.erlang-lsp]
command = "elp"
args = ["server"]

[[language]]
name = "markdown"
language-servers = ["harper-ls"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "t" }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "t" }

[[language]]
name = "typst"
language-servers = ["harper-ls"]

[[language]]
name = "erlang"
language-servers = ["erlang-lsp"]

[[language]]
name = "c"
indent = { tab-width = 4, unit = "t" }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "t" }

[[language]]
name = "janet"
indent = { tab-width = 4, unit = "t" }
